version: '3'

services:
  schema-collaboration:
    image: schema-collaboration
    environment:
      SECRET_KEY: ${SECRET_KEY}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      FORCE_SQLITE3_DATABASE: ${FORCE_SQLITE3_DATABASE}

      # If FORCE_SQLITE3_DATABASE the next DB_ settings are not used
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}

      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      DATAMANAGER_USERNAME: ${DATAMANAGER_USERNAME}
      DATAMANAGER_FULL_NAME: ${DATAMANAGER_FULL_NAME}
      DATAMANAGER_PASSWORD: ${DATAMANAGER_PASSWORD}
    ports:
      - "8000:80"
